/*
生成されたこのファイルは、
この管理グローバルクラスの実際のソースコードではありません。
この参照のみのファイルには、クラスのグローバルコンストラクタ、
メソッド、変数、プロパティが表示されます。
コードをコンパイルできるようにするには、すべてのメソッドで null を返します。
*/
global class jsButtonMethods {
    global jsButtonMethods() {

    }
    webService static String activateTriggeredSend(String trigSendId) {
        return null;
    }
    webService static String getPACId(String acctId) {
        return null;
    }
    webService static Boolean isETIntegrated() {
        return null;
    }
    webService static String namespace() {
        return null;
    }
    webService static String pauseTriggeredSend(String trigSendId) {
        return null;
    }
    webService static String performResub(String subKey, String objectType) {
        return null;
    }
    webService static String performUnsub(String subKey, String objectType) {
        return null;
    }
    webService static String saveRemember(et4ae5.jsButtonMethods.rememberParams params) {
        return null;
    }
global class rememberParams {
    @WebService
    webService String isChecked;
    @WebService
    webService String url;
    @WebService
    webService String userId;
    global rememberParams() {

    }
}
}
