/*
生成されたこのファイルは、
この管理グローバルクラスの実際のソースコードではありません。
この参照のみのファイルには、クラスのグローバルコンストラクタ、
メソッド、変数、プロパティが表示されます。
コードをコンパイルできるようにするには、すべてのメソッドで null を返します。
*/
global class mockHttpResponseGenerator implements System.HttpCalloutMock {
    global String myBody;
    global String status;
    global Integer statusCode;
    global mockHttpResponseGenerator() {

    }
    global mockHttpResponseGenerator(String bodyString) {

    }
    global System.HttpResponse respond(System.HttpRequest req) {
        return null;
    }
}
