/*
生成されたこのファイルは、
この管理グローバルクラスの実際のソースコードではありません。
この参照のみのファイルには、クラスのグローバルコンストラクタ、
メソッド、変数、プロパティが表示されます。
コードをコンパイルできるようにするには、すべてのメソッドで null を返します。
*/
global class trackingWebServices {
    global trackingWebServices() {

    }
    webService static String buttonResponse(String sendDefId) {
        return null;
    }
    webService static void cancelSendDef(String sendDefId) {

    }
    webService static void cancelSmsDef(String smsDefId) {

    }
    webService static void immediateTracking(String sendDefId, String evalString) {

    }
}
